import DashboardLayout from "@/components/layout/DashboardLayout";
import SubmitButton from "@/components/platform/SubmitButton";
import { requirePermission } from "@/src/lib/auth";
import { createDocumentAction } from "@/src/server/platform/actions";
import { getDocuments } from "@/src/server/platform/documents";
import type { DocumentCategory } from "@/src/generated/prisma/enums";
export const dynamic = "force-dynamic";
const documentCategories: DocumentCategory[] = ["GENERAL","VEHICLE","DRIVER","CUSTOMER","JOB","INVOICE","MAINTENANCE","FUEL","COMPLIANCE"];
const one = (value?: string | string[]) => Array.isArray(value) ? value[0] : value;
export default async function DocumentsPage({ searchParams }: { searchParams: Promise<{ q?: string | string[]; category?: string | string[] }> }) {
  const account = await requirePermission("documents:view"); const params = await searchParams; const q = one(params.q)?.trim(); const rawCategory = one(params.category); const category = documentCategories.includes(rawCategory as DocumentCategory) ? rawCategory as DocumentCategory : undefined; const documents = await getDocuments({ search: q, category });
  return <DashboardLayout title="Document Centre" subtitle="Shared metadata and entity-linked records."><div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><div className="space-y-5"><form className="flex gap-3"><input name="q" defaultValue={q} placeholder="Search documents…" className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-white" /><select name="category" defaultValue={category ?? ""} className="rounded-xl border border-slate-700 bg-slate-900 px-3 text-white"><option value="">All categories</option>{documentCategories.map(item => <option key={item}>{item}</option>)}</select><button className="rounded-xl bg-slate-700 px-4 text-white">Filter</button></form>
    <div className="space-y-3">{documents.map(document => <article key={document.id} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between"><div><span className="text-xs text-blue-400">{document.category}</span><h2 className="mt-1 font-semibold text-white">{document.name}</h2><p className="mt-1 text-sm text-slate-400">{document.description || "No description"}</p></div>{document.externalUrl && <a href={document.externalUrl} target="_blank" rel="noreferrer" className="text-sm text-blue-400">Open</a>}</div><p className="mt-3 text-xs text-slate-500">{document.entityType ? `${document.entityType} · ${document.entityId || "unlinked"}` : "General"} · {document.createdAt.toLocaleDateString("en-GB")}</p></article>)}{documents.length === 0 && <p className="rounded-xl border border-slate-800 bg-slate-900 p-10 text-center text-slate-500">No documents match these filters.</p>}</div></div>
    <aside className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold text-white">Add document metadata</h2><p className="mt-2 text-xs text-slate-500">Storage is not configured, so this release records an approved external link or metadata placeholder.</p><form action={createDocumentAction} className="mt-5 space-y-4"><input required name="name" placeholder="Document name" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" /><textarea name="description" placeholder="Description" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" /><select name="category" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white">{documentCategories.map(item => <option key={item}>{item}</option>)}</select><input name="entityType" placeholder="Entity type (e.g. Truck)" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" /><input name="entityId" placeholder="Entity ID" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" /><input name="externalUrl" type="url" placeholder="https://…" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" />{account.role === "DRIVER" ? <p className="text-sm text-amber-300">Drivers have read-only document access.</p> : <SubmitButton>Add document</SubmitButton>}</form></aside>
  </div></DashboardLayout>;
}
