import Link from "next/link";
import { notFound } from "next/navigation";
import DashboardLayout from "@/components/layout/DashboardLayout";
import InvoiceStatusBadge from "@/components/finance/InvoiceStatusBadge";
import { getInvoice } from "@/src/server/finance/service";
export const dynamic = "force-dynamic";
const money = new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" });
const date = new Intl.DateTimeFormat("en-GB", { dateStyle: "long" });
export default async function InvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const invoice = await getInvoice(id); if (!invoice) notFound();
  const balance = Math.max(0, invoice.total - invoice.amountPaid); const overdue = invoice.dueDate < new Date() && !["PAID", "VOID"].includes(invoice.status);
  const rows = [["Subtotal", money.format(invoice.subtotal)], [`VAT (${invoice.vatRate}%)`, money.format(invoice.vatAmount)], ["Total", money.format(invoice.total)], ["Paid", money.format(invoice.amountPaid)], ["Balance", money.format(balance)]];
  const journey = invoice.driverPerformanceEntry;
  return <DashboardLayout title={invoice.invoiceNumber} subtitle="Customer invoice record."><div className="mx-auto max-w-5xl space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><Link href="/dashboard/finance" className="text-sm text-violet-400 hover:text-violet-300">← Finance Centre</Link><div className="mt-2 flex items-center gap-3"><h1 className="text-3xl font-bold text-white">{invoice.invoiceNumber}</h1><InvoiceStatusBadge status={invoice.status} overdue={overdue} /></div><p className="mt-2 text-slate-400">{invoice.customer.companyName}</p></div><Link href={`/dashboard/finance/${invoice.id}/edit`} className="rounded-lg bg-violet-600 px-4 py-2 text-center font-medium text-white hover:bg-violet-500">Edit invoice</Link></div>
    <div className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-semibold text-white">{invoice.description}</h2><dl className="mt-6 grid gap-5 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Issue date</dt><dd className="mt-1 text-slate-200">{date.format(invoice.issueDate)}</dd></div><div><dt className="text-sm text-slate-500">Due date</dt><dd className={`mt-1 ${overdue ? "font-semibold text-red-300" : "text-slate-200"}`}>{date.format(invoice.dueDate)}</dd></div><div><dt className="text-sm text-slate-500">Customer number</dt><dd className="mt-1 text-slate-200">{invoice.customer.customerNumber}</dd></div><div><dt className="text-sm text-slate-500">Reference</dt><dd className="mt-1 text-slate-200">{invoice.reference || "—"}</dd></div><div><dt className="text-sm text-slate-500">Billing email</dt><dd className="mt-1 text-slate-200">{invoice.customer.billingEmail || invoice.customer.email}</dd></div><div><dt className="text-sm text-slate-500">Paid on</dt><dd className="mt-1 text-slate-200">{invoice.paidAt ? date.format(invoice.paidAt) : "—"}</dd></div></dl>{invoice.notes && <div className="mt-6 border-t border-slate-800 pt-6"><p className="text-sm text-slate-500">Internal notes</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{invoice.notes}</p></div>}</section>
    <section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-semibold text-white">Invoice summary</h2><dl className="mt-5 divide-y divide-slate-800">{rows.map(([label, value], index) => <div key={label} className={`flex justify-between py-3 ${index === rows.length - 1 ? "text-lg font-bold text-white" : "text-sm text-slate-300"}`}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section></div>
    {journey && <section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-semibold text-white">Journey profitability</h2><p className="mt-1 text-sm text-slate-400">Internal costs are shown for management reporting and are not added to the customer charge.</p><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-sm text-slate-500">Job income</dt><dd className="mt-1 font-semibold text-emerald-300">{money.format(journey.income)}</dd></div><div><dt className="text-sm text-slate-500">Repairs</dt><dd className="mt-1 text-slate-200">{money.format(journey.repairCosts)}</dd></div><div><dt className="text-sm text-slate-500">Damage</dt><dd className="mt-1 text-slate-200">{money.format(journey.damageCosts)}</dd></div><div><dt className="text-sm text-slate-500">Other costs</dt><dd className="mt-1 text-slate-200">{money.format(journey.otherCosts)}</dd></div><div><dt className="text-sm text-slate-500">Operating profit</dt><dd className={`mt-1 font-bold ${journey.income - journey.expenditure >= 0 ? "text-emerald-300" : "text-red-300"}`}>{money.format(journey.income - journey.expenditure)}</dd></div><div><dt className="text-sm text-slate-500">Driver</dt><dd className="mt-1 text-slate-200">{journey.driver.account.firstName} {journey.driver.account.lastName}</dd></div><div><dt className="text-sm text-slate-500">Distance</dt><dd className="mt-1 text-slate-200">{journey.distanceKm.toLocaleString("en-GB")} km</dd></div><div><dt className="text-sm text-slate-500">Cargo</dt><dd className="mt-1 text-slate-200">{journey.cargoTonnes.toLocaleString("en-GB")} t</dd></div></dl></section>}
  </div></DashboardLayout>;
}
