import DashboardLayout from "@/components/layout/DashboardLayout";
import SubmitButton from "@/components/platform/SubmitButton";
import { requirePermission } from "@/src/lib/auth";
import { updateSettingsAction } from "@/src/server/platform/actions";
import { getSettingsCentre } from "@/src/server/platform/settings";
export const dynamic = "force-dynamic";
export default async function SettingsPage() {
  const account = await requirePermission("settings:view"); const company = await getSettingsCentre();
  if (!company) return <DashboardLayout title="Settings Centre"><div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-8 text-amber-200">Create the company record before configuring enterprise settings.</div></DashboardLayout>;
  const s = company.settings;
  return <DashboardLayout title="Settings Centre" subtitle="Company, finance, branding and integration defaults."><div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><form action={updateSettingsAction} className="rounded-xl border border-slate-800 bg-slate-900 p-6"><input type="hidden" name="companyId" value={company.id} /><div className="grid gap-5 md:grid-cols-2">{[
    ["legalName","Legal name",s?.legalName ?? company.name],["tradingName","Trading name",s?.tradingName ?? company.name],["registrationNo","Company number",s?.registrationNo ?? ""],["vatNumber","VAT number",s?.vatNumber ?? ""],["phone","Phone",s?.phone ?? ""],["email","Email",s?.email ?? ""],["website","Website",s?.website ?? ""],["primaryColour","Brand colour",s?.primaryColour ?? "#2563eb"],["vatRate","VAT rate (%)",String(s?.vatRate ?? 20)],["invoicePrefix","Invoice prefix",s?.invoicePrefix ?? "INV"],
  ].map(([name,label,value]) => <label key={name} className="text-sm text-slate-300">{label}<input name={name} defaultValue={value} required={name === "legalName"} type={name === "email" ? "email" : name === "website" ? "url" : name === "vatRate" ? "number" : name === "primaryColour" ? "color" : "text"} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" /></label>)}</div><label className="mt-5 block text-sm text-slate-300">Address<textarea name="address" defaultValue={s?.address ?? ""} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" /></label><div className="mt-6">{account.role === "CEO" ? <SubmitButton>Save settings</SubmitButton> : <p className="text-sm text-slate-500">Only the CEO can change company-wide settings.</p>}</div></form>
    <aside className="space-y-5"><section className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold text-white">Fixed regional defaults</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Currency</dt><dd className="text-white">GBP</dd></div><div className="flex justify-between"><dt className="text-slate-500">Locale</dt><dd className="text-white">en-GB</dd></div></dl></section><section className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold text-white">Depots</h2><ul className="mt-3 space-y-2 text-sm text-slate-300">{company.depots.map(depot => <li key={depot.id}>{depot.name} · {depot.city}</li>)}</ul></section><section className="rounded-xl border border-dashed border-slate-700 p-5"><h2 className="font-semibold text-white">Integrations</h2><p className="mt-2 text-sm text-slate-500">Accounting, telematics, storage and messaging connectors are ready for provider configuration.</p></section></aside>
  </div></DashboardLayout>;
}
