"use client";
import Link from "next/link";
import { useActionState, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle, Loader2, Save } from "lucide-react";
import { createContractListingAction, type MarketplaceActionState } from "@/src/server/marketplace/actions";
import { cargoCategories, cargoLabels, compatibleTrailers, trailerLabels, type CargoCategory } from "@/src/lib/ets2-trailers";
type Customer = Awaited<ReturnType<typeof import("@/src/server/marketplace/service").getMarketplaceCustomers>>[number];
const initial: MarketplaceActionState = { success: false, message: "" };
const input = "w-full rounded-lg border border-slate-700 bg-slate-950 px-4 py-3 text-sm text-white outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-500/20";
function Field({ name, title, error, children }: { name: string; title: string; error?: string[]; children: React.ReactNode }) { return <div><label htmlFor={name} className="mb-2 block text-sm font-medium text-slate-300">{title}</label>{children}{error?.[0] && <p className="mt-2 text-sm text-red-400">{error[0]}</p>}</div>; }
export default function ContractListingForm({ customers }: { customers: Customer[] }) {
  const router = useRouter(); const [state, action, pending] = useActionState(createContractListingAction, initial);
  const [cargoCategory, setCargoCategory] = useState<CargoCategory>("GENERAL");
  useEffect(() => { if (state.success && state.listingId) { router.push(`/dashboard/marketplace/${state.listingId}`); router.refresh(); } }, [state, router]);
  return <form action={action} className="space-y-6"><section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-semibold text-white">Opportunity</h2><div className="mt-6 grid gap-6 md:grid-cols-2">
    <Field name="customerId" title="Customer" error={state.fieldErrors?.customerId}><select id="customerId" name="customerId" required className={input}><option value="">Select customer</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.customerNumber} · {customer.companyName}</option>)}</select></Field>
    <Field name="title" title="Contract title" error={state.fieldErrors?.title}><input id="title" name="title" required className={input} placeholder="Weekly chilled freight to Manchester" /></Field>
    <div className="md:col-span-2"><Field name="description" title="Scope" error={state.fieldErrors?.description}><textarea id="description" name="description" rows={4} required className={input} placeholder="Cargo, handling, frequency and service requirements…" /></Field></div>
    <Field name="origin" title="Origin" error={state.fieldErrors?.origin}><input id="origin" name="origin" required className={input} placeholder="Birmingham, UK" /></Field><Field name="destination" title="Destination" error={state.fieldErrors?.destination}><input id="destination" name="destination" required className={input} placeholder="Manchester, UK" /></Field>
    <Field name="cargoType" title="Cargo type" error={state.fieldErrors?.cargoType}><input id="cargoType" name="cargoType" required className={input} placeholder="Palletised chilled goods" /></Field><Field name="weightKg" title="Weight (kg)" error={state.fieldErrors?.weightKg}><input id="weightKg" name="weightKg" type="number" min="1" step="0.01" className={input} /></Field>
    <Field name="cargoCategory" title="ETS2 cargo category" error={state.fieldErrors?.cargoCategory}><select id="cargoCategory" name="cargoCategory" value={cargoCategory} onChange={(event) => setCargoCategory(event.target.value as CargoCategory)} required className={input}>{cargoCategories.map((category) => <option key={category} value={category}>{cargoLabels[category]}</option>)}</select></Field>
    <Field name="requiredTrailer" title="Required ETS2 trailer" error={state.fieldErrors?.requiredTrailer}><select id="requiredTrailer" name="requiredTrailer" required className={input}>{compatibleTrailers[cargoCategory].map((trailer) => <option key={trailer} value={trailer}>{trailerLabels[trailer]}</option>)}</select></Field>
    <Field name="pickupDate" title="Pickup date" error={state.fieldErrors?.pickupDate}><input id="pickupDate" name="pickupDate" type="date" required className={input} /></Field><Field name="deliveryDate" title="Delivery date" error={state.fieldErrors?.deliveryDate}><input id="deliveryDate" name="deliveryDate" type="date" required className={input} /></Field>
    <Field name="budget" title="Maximum contract value" error={state.fieldErrors?.budget}><input id="budget" name="budget" type="number" min="0.01" step="0.01" required className={input} /></Field><Field name="currency" title="Currency" error={state.fieldErrors?.currency}><select id="currency" name="currency" defaultValue="GBP" className={input}><option value="GBP">GBP</option><option value="EUR">EUR</option><option value="USD">USD</option></select></Field>
    <div className="md:col-span-2"><Field name="contractTerms" title="Smart contract terms" error={state.fieldErrors?.contractTerms}><textarea id="contractTerms" name="contractTerms" rows={5} required className={input} placeholder="Payment trigger, proof of delivery, delay clauses and acceptance criteria…" /></Field></div><label className="md:col-span-2 flex items-center gap-3 text-sm text-slate-300"><input name="publish" type="checkbox" className="h-4 w-4 rounded border-slate-600 bg-slate-950 text-cyan-500" />Publish immediately and accept bids</label>
  </div></section>{state.message && !state.success && <div className="flex gap-3 rounded-lg border border-red-500/30 bg-red-500/10 p-4 text-red-300"><AlertCircle className="h-5 w-5" /><p className="text-sm">{state.message}</p></div>}<div className="flex justify-end gap-3"><Link href="/dashboard/marketplace" className="rounded-lg border border-slate-700 bg-slate-900 px-5 py-3 text-sm text-slate-300 hover:bg-slate-800">Cancel</Link><button disabled={pending} className="inline-flex items-center gap-2 rounded-lg bg-cyan-600 px-5 py-3 text-sm font-semibold text-white hover:bg-cyan-500 disabled:opacity-60">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Create contract</button></div></form>;
}
