import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
type Listing = Awaited<ReturnType<typeof import("@/src/server/marketplace/service").getContractMarketplace>>["listings"][number];
const money = new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 });
const badge: Record<string, string> = { DRAFT: "bg-slate-700 text-slate-200", OPEN: "bg-emerald-500/15 text-emerald-300", AWARDED: "bg-violet-500/15 text-violet-300", CLOSED: "bg-blue-500/15 text-blue-300", CANCELLED: "bg-red-500/15 text-red-300" };
export default function MarketplaceTable({ listings }: { listings: Listing[] }) {
  if (!listings.length) return <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900 p-12 text-center"><h2 className="font-semibold text-white">No marketplace contracts found</h2><p className="mt-2 text-sm text-slate-400">Create a contract opportunity or adjust the current filters.</p></div>;
  return <div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-800 bg-slate-950/50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Contract</th><th className="px-5 py-4">Route</th><th className="px-5 py-4">Pickup</th><th className="px-5 py-4">Budget</th><th className="px-5 py-4">Bids</th><th className="px-5 py-4">Status</th><th /></tr></thead><tbody className="divide-y divide-slate-800">{listings.map((listing) => <tr key={listing.id} className="hover:bg-slate-800/40"><td className="px-5 py-4"><Link href={`/dashboard/marketplace/${listing.id}`} className="font-semibold text-white hover:text-cyan-300">{listing.title}</Link><p className="mt-1 text-xs text-slate-500">{listing.reference} · {listing.customer.companyName}</p></td><td className="px-5 py-4 text-slate-300"><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-cyan-400" />{listing.origin} <ArrowRight className="h-3 w-3" /> {listing.destination}</span></td><td className="px-5 py-4 text-slate-400">{listing.pickupDate.toLocaleDateString("en-GB")}</td><td className="px-5 py-4 font-medium text-white">{money.format(listing.budget)}</td><td className="px-5 py-4 text-slate-300">{listing.bids.length}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${badge[listing.status]}`}>{listing.status.toLowerCase()}</span></td><td className="px-5 py-4 text-right"><Link href={`/dashboard/marketplace/${listing.id}`} className="text-cyan-400 hover:text-cyan-300">View</Link></td></tr>)}</tbody></table></div></div>;
}
