import Link from "next/link";
import { Fuel } from "lucide-react";

type Entry = Awaited<ReturnType<typeof import("@/src/server/fuel/service").getFuelCentre>>["entries"][number];
const money = (value: number) => value.toLocaleString("en-GB", { style: "currency", currency: "GBP" });

export default function FuelTable({ entries }: { entries: Entry[] }) {
  if (!entries.length) return <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900/50 px-6 py-16 text-center"><Fuel className="mx-auto h-10 w-10 text-slate-600" /><h2 className="mt-4 text-lg font-semibold text-white">No fuel entries found</h2><p className="mt-1 text-sm text-slate-400">Record a fill-up or adjust the filters.</p></div>;
  return <div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-800 bg-slate-950/60 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Reference</th><th className="px-5 py-4">Vehicle</th><th className="px-5 py-4">Fuel</th><th className="px-5 py-4">Station</th><th className="px-5 py-4 text-right">Quantity</th><th className="px-5 py-4 text-right">Cost</th><th className="px-5 py-4">Purchased</th></tr></thead><tbody className="divide-y divide-slate-800">{entries.map((entry) => <tr key={entry.id} className="hover:bg-slate-800/50"><td className="px-5 py-4"><Link href={`/dashboard/fuel/${entry.id}`} className="font-semibold text-cyan-400 hover:text-cyan-300">{entry.reference}</Link></td><td className="px-5 py-4 text-white">{entry.truck.fleetNumber}<span className="block text-xs text-slate-500">{entry.truck.registration}</span></td><td className="px-5 py-4 text-slate-300">{entry.fuelType}</td><td className="px-5 py-4 text-slate-300">{entry.station}</td><td className="px-5 py-4 text-right text-slate-300">{entry.quantity.toLocaleString("en-GB")} {entry.fuelType === "ELECTRIC" ? "kWh" : "L"}</td><td className="px-5 py-4 text-right font-medium text-white">{money(entry.totalCost)}</td><td className="px-5 py-4 text-slate-400">{new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(entry.purchasedAt)}</td></tr>)}</tbody></table></div></div>;
}
