ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'WORKSHOP';
CREATE TYPE "NotificationSeverity" AS ENUM ('INFO', 'SUCCESS', 'WARNING', 'CRITICAL');
CREATE TYPE "NotificationType" AS ENUM ('SYSTEM', 'FLEET', 'DRIVER', 'DISPATCH', 'WORKSHOP', 'FUEL', 'CUSTOMER', 'FINANCE', 'DOCUMENT');
CREATE TYPE "DocumentCategory" AS ENUM ('GENERAL', 'VEHICLE', 'DRIVER', 'CUSTOMER', 'JOB', 'INVOICE', 'MAINTENANCE', 'FUEL', 'COMPLIANCE');
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "recipientId" TEXT, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "type" "NotificationType" NOT NULL DEFAULT 'SYSTEM', "severity" "NotificationSeverity" NOT NULL DEFAULT 'INFO', "entityType" TEXT, "entityId" TEXT, "entityHref" TEXT, "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "expiresAt" TIMESTAMP(3), CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Document" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "category" "DocumentCategory" NOT NULL DEFAULT 'GENERAL', "entityType" TEXT, "entityId" TEXT, "storageKey" TEXT, "originalName" TEXT, "mimeType" TEXT, "sizeBytes" INTEGER, "externalUrl" TEXT, "uploadedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "archivedAt" TIMESTAMP(3), CONSTRAINT "Document_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditEvent" ("id" TEXT NOT NULL, "actorId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT, "summary" TEXT NOT NULL, "before" JSONB, "after" JSONB, "ipAddress" TEXT, "userAgent" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CompanySettings" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "legalName" TEXT NOT NULL, "tradingName" TEXT, "registrationNo" TEXT, "vatNumber" TEXT, "address" TEXT, "phone" TEXT, "email" TEXT, "website" TEXT, "logoUrl" TEXT, "primaryColour" TEXT NOT NULL DEFAULT '#2563eb', "currency" TEXT NOT NULL DEFAULT 'GBP', "locale" TEXT NOT NULL DEFAULT 'en-GB', "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 20, "invoicePrefix" TEXT NOT NULL DEFAULT 'INV', "nextInvoiceNo" INTEGER NOT NULL DEFAULT 1, "notificationPreferences" JSONB, "integrations" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CompanySettings_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "CompanySettings_companyId_key" ON "CompanySettings"("companyId");
CREATE INDEX "Notification_recipientId_readAt_createdAt_idx" ON "Notification"("recipientId", "readAt", "createdAt");
CREATE INDEX "Notification_type_createdAt_idx" ON "Notification"("type", "createdAt");
CREATE INDEX "Notification_entityType_entityId_idx" ON "Notification"("entityType", "entityId");
CREATE INDEX "Document_category_createdAt_idx" ON "Document"("category", "createdAt");
CREATE INDEX "Document_entityType_entityId_idx" ON "Document"("entityType", "entityId");
CREATE INDEX "Document_uploadedById_idx" ON "Document"("uploadedById");
CREATE INDEX "Document_archivedAt_idx" ON "Document"("archivedAt");
CREATE INDEX "AuditEvent_createdAt_idx" ON "AuditEvent"("createdAt");
CREATE INDEX "AuditEvent_actorId_createdAt_idx" ON "AuditEvent"("actorId", "createdAt");
CREATE INDEX "AuditEvent_action_createdAt_idx" ON "AuditEvent"("action", "createdAt");
CREATE INDEX "AuditEvent_entityType_entityId_idx" ON "AuditEvent"("entityType", "entityId");
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_recipientId_fkey" FOREIGN KEY ("recipientId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CompanySettings" ADD CONSTRAINT "CompanySettings_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
