import Link from "next/link";
import { ContactRound } from "lucide-react";
import CustomerStatusBadge from "./CustomerStatusBadge";

type Customer = Awaited<ReturnType<typeof import("@/src/server/customers/service").getCustomerCRM>>["customers"][number];
const money = (value: number) => value.toLocaleString("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 });

export default function CustomerTable({ customers }: { customers: Customer[] }) {
  if (!customers.length) return <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900/50 px-6 py-16 text-center"><ContactRound className="mx-auto h-10 w-10 text-slate-600" /><h2 className="mt-4 text-lg font-semibold text-white">No customers found</h2><p className="mt-1 text-sm text-slate-400">Add a customer or adjust the filters.</p></div>;
  return <div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-800 bg-slate-950/60 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Account</th><th className="px-5 py-4">Company</th><th className="px-5 py-4">Primary contact</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Location</th><th className="px-5 py-4 text-right">Credit limit</th></tr></thead><tbody className="divide-y divide-slate-800">{customers.map((customer) => <tr key={customer.id} className={customer.archivedAt ? "opacity-55 hover:bg-slate-800/50" : "hover:bg-slate-800/50"}><td className="px-5 py-4"><Link href={`/dashboard/customers/${customer.id}`} className="font-semibold text-violet-400 hover:text-violet-300">{customer.customerNumber}</Link>{customer.archivedAt && <span className="mt-1 block text-xs text-slate-500">Archived</span>}</td><td className="px-5 py-4 font-medium text-white">{customer.companyName}</td><td className="px-5 py-4 text-slate-300">{customer.contactFirstName} {customer.contactLastName}<span className="block text-xs text-slate-500">{customer.email}</span></td><td className="px-5 py-4"><CustomerStatusBadge status={customer.status} /></td><td className="px-5 py-4 text-slate-400">{[customer.city, customer.country].filter(Boolean).join(", ") || "Not recorded"}</td><td className="px-5 py-4 text-right text-slate-200">{customer.creditLimit === null ? "Not set" : money(customer.creditLimit)}</td></tr>)}</tbody></table></div></div>;
}
